name: assign-reviewer

on: push
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  pull-requests: write
jobs:
  get_pr_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: matrix
        name: filter past 1day PR && format github actions matrix
        run: |
          pr_list=$(gh pr list --search "created:<=`TZ=UTC+9 date -d "now 1days ago"  "+%Y-%m-%d"` state:open" --json number | jq '[.[].number]')
          echo "::set-output name=value::$(echo $pr_list | jq -c .)"
  assign_pr:
    needs: get_pr_matrix
    if: needs.get_pr_matrix.outputs.matrix != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJson(needs.get_pr_matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: assign reviewer
        run: |
          gh pr edit ${{ matrix.value }} --add-reviewer pep299
