name: dbd-bot-ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'drawio'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'drawio'
permissions:
  discussions: write
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install portry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Poetry Version
        run: |
          poetry --version
      - name: Poetry Install Dependencies
        run: |
          poetry install --no-interaction
      - name: Test with pytest
        run: |
          poetry run pytest --junitxml=pytest.xml --cov-report=term-missing --cov=src | tee pytest-coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: app/pytest-coverage.txt
          junitxml-path: app/pytest.xml
          coverage-path-prefix: app
  aws_cdk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cdk
    env:
      AWS_DEFAULT_REGION: 'us-east-2'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
      LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_KEY_NAME: ${{ secrets.S3_KEY_NAME }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Setup dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: CDK diff check
        if: contains(github.event_name, 'pull_request')
        run: npm run cdk:diff

      - name: CDK deploy
        if: contains(github.event_name, 'push')
        run: npm run cdk:deploy
